/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainUI;

import Bedroom.Bedroom;
import HashTable.HashTable;
import Lista.Lista;
import Reservation.Reservation;
import User.User;
import java.io.FileInputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.DateUtil;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author User
 */
public class MainUI extends javax.swing.JFrame {

    HashTable b;

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        b = new HashTable(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 83, -1, -1));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void leerExcel() {
        XSSFWorkbook libro = null;
        try {
            //abrimos el XSSFWorkbook
            FileInputStream f = new FileInputStream("C:\\Users\\User\\Desktop\\Trabajo.xlsx");

            libro = new XSSFWorkbook(f);
        } catch (Exception e) {

        }
        Bedroom[] habs = null;
        int maximoIndice = libro.getNumberOfSheets();
        for (int i = 0; i < maximoIndice; i++) {
            XSSFSheet hoja = libro.getSheetAt(i);
            String nombreHoja = hoja.getSheetName();
            switch (nombreHoja) {
//                case "Reservas":
//
//                    Lista reservas = reservas(hoja);
//                    System.out.println(reservas.size());
//                    break;
                case "Habitaciones":
                    System.out.println("skfaklfsalfkf;af");
                    habs = Habitaciones(hoja);
                    break;
//
                case "Estado":
                    if (habs == null) {
                        throw new Error("Error");
                    }
//                    HashTable statusHabs = status(hoja, habs);
                    break;
                case "Historico":
                    if (habs == null) {
                        throw new Error("Error");
                    }
                    historico(hoja, habs);
                    break;
            }
        }

//            //seleccionamos la primera hoja
//            XSSFSheet hoja = libro.getSheetAt(0);
//
//            //Cogemos todas las filas de esa hoja
//            Iterator<Row> filas = hoja.iterator();
//            Iterator<Cell> columnas;
//
//            Row fila;
//            Cell columna;
//            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//            //recorremos las filas
//            Lista reservaciones = new Lista();
//            fila = filas.next();
//
//            while (filas.hasNext()) {
//                int n = 0;
//                //Cogemos la siguiente fila
//                fila = filas.next();
//
//                //Cogemos todas las celdas de esa fila
//                columnas = fila.cellIterator();
//                int dni = 0;
//                String name = "";
//                String last_name = "";
//                String gener = "";
//                String email = "";
//                String phone = "";
//                String ride = "";
//                String departure = "";
//                String type="";
//
//                //REcorremos todas las celdas
//                while (columnas.hasNext()) {
//                    n++;
//                    //Cogemos la siguiente fila
//                    columna = columnas.next();
//
//                    //Segun el tipo de celda, usaremos uno u otra funcion
//                    if (n == 1) {
//                        double i = columna.getNumericCellValue();
//                        String value = String.valueOf(i);
//                        value = value.replace(".", "");
//                        value = value.replace("E7", "");
//                        dni = Integer.parseInt(value);
//                        System.out.println(value);
//                    } else if (n == 2) {
//                        name = columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
//
//                    } else if (n == 3) {
//                        last_name = columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
//                    } else if (n == 4) {
//                        email = columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
//                    } else if (n == 5) {
//                        gener = columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
//                    } else if (n == 6) {
//                        type=columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
//                    } else if (n == 7) {
//                        phone = columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
//                    } else if (n == 8) {
//                        String a = String.valueOf(columna.getDateCellValue());
//                        ride = a;
//
//                        System.out.println("Fecha: " + a);
//                    } else {
//                        String a = String.valueOf(columna.getDateCellValue());
//                        departure = a;
//                        System.out.println("Fecha: " + a);
//                    }
//
//                }
//                User u= new User(dni,  name,  last_name,  gener,  email,  phone);
//                u.setRide(ride);
//                u.setDeparture(departure);
//                Reservation r= new Reservation (u,type);
//                reservaciones.addLast(r);
//            }
//            HashTable statusHabs = status(libro, habs);
//            this.b = statusHabs;
//           System.out.println(u.getNum());
        //cerramos el libro
//        } catch (Exception e) {
//            System.out.print("Error");
//
//        }
    }

    public Lista reservas(XSSFSheet hoja) {
        Lista ord = new Lista();
        int n = 0;
        int rowIndex = 0; // Índice de la primera fila

        Row row = hoja.getRow(rowIndex); // Obtiene la primera fila

        if (row != null) {
            int cellIndexStart = row.getFirstCellNum(); // Índice de la primera celda
            int cellIndexEnd = row.getLastCellNum(); // Índice de la última celda

            for (int cellIndex = cellIndexStart; cellIndex < 9; cellIndex++) {
                Cell cell = row.getCell(cellIndex);
                n++;
                String[] posicion = new String[2];

                if (cell != null) {

                    if ("ci".equals(cell.getStringCellValue())) {
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        posicion[0] = "ci";

                        ord.addLast(posicion);
                    } else if ("primer_nombre".equals(cell.getStringCellValue())) {
                        posicion[0] = "primer_nombre";
                        String p = String.valueOf(n);
                        posicion[1] = p;

                        ord.addLast(posicion);
                    } else if ("segundo_nombre".equals(cell.getStringCellValue())) {
                        posicion[0] = "segundo_nombre";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("email".equals(cell.getStringCellValue())) {
                        posicion[0] = "email";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("genero".equals(cell.getStringCellValue())) {
                        posicion[0] = "genero";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("tipo_hab".equals(cell.getStringCellValue())) {
                        posicion[0] = "tipo_hab";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("celular".equals(cell.getStringCellValue())) {
                        posicion[0] = "celular";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("llegada".equals(cell.getStringCellValue())) {
                        posicion[0] = "llegada";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("salida".equals(cell.getStringCellValue())) {
                        posicion[0] = "salida";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else {

                    }

                }

            }
        }

        Cell columna;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//            recorremos las filas
        Lista reservaciones = new Lista();
        // Índice de la segunda fila

        int rowIndexEnd = hoja.getLastRowNum();

        for (int p = 1; p <= rowIndexEnd; p++) {
            row = hoja.getRow(p); // Obtiene la fila por índice
            n = 0;
            if (row != null) {
                int cellIndexStart = row.getFirstCellNum(); // Índice de la primera celda
                int cellIndexEnd = row.getLastCellNum();

                for (int cellIndex = cellIndexStart; cellIndex < cellIndexEnd; cellIndex++) {
                    columna = row.getCell(cellIndex); // Obtiene la celda por índice

//                Cogemos la siguiente fila
//
//                Cogemos todas las celdas de esa fila
                    int dni = 0;
                    String name = "";
                    String last_name = "";
                    String gener = "";
                    String email = "";
                    String phone = "";
                    String ride = "";
                    String departure = "";
                    String type = "";

//                REcorremos todas las celdas
                    n++;
//                    Cogemos la siguiente fila

                    String[] orden = (String[]) ord.search2(n);
                    System.out.println(orden[0]);
                    switch (orden[0]) {
                        case "ci":
                            double i = columna.getNumericCellValue();
                            String value = String.valueOf(i);
                            value = value.replace(".", "");
                            value = value.replace("E7", "");
                            dni = Integer.parseInt(value);
//                        System.out.println(value);
                            break;
                        case "primer_nombre":
                            name = columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
                            break;

                        case "segundo_nombre":
                            last_name = columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
                            break;
                        case "email":
                            email = columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
                            break;
                        case "genero":
                            gener = columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
                            break;
                        case "tipo_hab":
                            type = columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
                            break;
                        case "celular":
                            phone = columna.getStringCellValue();
//                        System.out.println(columna.getStringCellValue());
                            break;
                        case "llegada":
                            String a = String.valueOf(columna.getDateCellValue());
                            ride = a;

//                        System.out.println("Fecha: " + a);
                            break;
                        case "salida":
                            String b = String.valueOf(columna.getDateCellValue());
                            departure = b;
//                        System.out.println("Fecha: " + b);
                            break;

                    }

                    try {
                        if (!"".equals(departure)) {
                            User u = new User(dni, name, last_name, gener, email, phone);
                            u.setRide(ride);
                            u.setDeparture(departure);
                            Reservation r = new Reservation(u, type);
                            reservaciones.addLast(r);
                        }
                    } catch (Exception e) {
                    }
                }
            }
        }
        return reservaciones;
    }

    public Bedroom[] Habitaciones(XSSFSheet hoja) {
        Lista ord = new Lista();
        int n = 0;
        int rowIndex = 0; // Índice de la primera fila

        Row row = hoja.getRow(rowIndex); // Obtiene la primera fila

        if (row != null) {
            int cellIndexStart = row.getFirstCellNum(); // Índice de la primera celda
            int cellIndexEnd = row.getLastCellNum(); // Índice de la última celda

            for (int cellIndex = cellIndexStart; cellIndex < 3; cellIndex++) {
                Cell cell = row.getCell(cellIndex);
                n++;
                String[] posicion = new String[2];

                if (cell != null) {
                    if ("num_hab".equals(cell.getStringCellValue())) {
                        posicion[0] = "num_hab";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("tipo_hab".equals(cell.getStringCellValue())) {
                        posicion[0] = "tipo_hab";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("piso".equals(cell.getStringCellValue())) {
                        posicion[0] = "piso";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else {

                    }

                }

            }
        }

        //Cogemos todas las filas de esa hoja
        Row fila;
        Cell columna;
        Lista habitaciones = new Lista();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//            recorremos las filas
        Lista reservaciones = new Lista();
        // Índice de la segunda fila

        int rowIndexEnd = hoja.getLastRowNum();

        for (int p = 1; p <= rowIndexEnd; p++) {
            row = hoja.getRow(p); // Obtiene la fila por índice
            n = 0;
            if (row != null) {
                int cellIndexStart = row.getFirstCellNum(); // Índice de la primera celda
                int cellIndexEnd = row.getLastCellNum();

                for (int cellIndex = cellIndexStart; cellIndex < cellIndexEnd; cellIndex++) {
                    columna = row.getCell(cellIndex); // Obtiene la celda por índice

                    //Cogemos la siguiente fila
                    //Cogemos todas las celdas de esa fila
                    String type = "";
                    int piso = 0;
                    String x = "";

                    //REcorremos todas las celdas
                    n++;
                    //Cogemos la siguiente fila

                    String[] orden = (String[]) ord.search2(n);

                    switch (orden[0]) {
                        case "tipo_hab":
                            type = columna.getStringCellValue();
//                            System.out.println(type);

                            break;
                        case "piso":
                            double i = columna.getNumericCellValue();
                            piso = (int) i;
//                            System.out.println(piso);
                            break;
                        default:
                            break;

                    }
                    //Segun el tipo de celda, usaremos uno u otra funcion
////                if (o != 0) {
////                    if (n == 2) {
////                        type = columna.getStringCellValue();
////                        System.out.println(columna.getStringCellValue());
////                    } else if ((columna.getCellType() == CellType.NUMERIC) && (n == 3)) {
////                        double i = columna.getNumericCellValue();
////                        piso = (int) i;
////                        System.out.println(piso);
////
////                    } else {
////                        continue;
////                    }
////                }
////            }
////            if (o != 0) {
                    try {
                        Bedroom b = new Bedroom(type, piso);
                        habitaciones.addLast(b);
                    } catch (Exception e) {

                    }

                }

            }

        }
        Bedroom habs[] = new Bedroom[(int) habitaciones.size()];

        for (int i = 0; i < habitaciones.size(); i++) {

            habs[i] = (Bedroom) habitaciones.getValuePosition(i);
        }
        return habs;

    }

    public HashTable status(XSSFSheet hoja, Bedroom habs[]) {
        Lista ord = new Lista();
        int n = 0;
        int rowIndex = 0; // Índice de la primera fila

        Row row = hoja.getRow(rowIndex); // Obtiene la primera fila

        if (row != null) {
            int cellIndexStart = row.getFirstCellNum(); // Índice de la primera celda
            int cellIndexEnd = row.getLastCellNum(); // Índice de la última celda

            for (int cellIndex = cellIndexStart; cellIndex < 10; cellIndex++) {
                Cell cell = row.getCell(cellIndex);
                n++;
                String[] posicion = new String[2];

                if (cell != null) {
                    if ("num_hab".equals(cell.getStringCellValue())) {
                        posicion[0] = "num_hab";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("primer_nombre".equals(cell.getStringCellValue())) {
                        posicion[0] = "primer_nombre";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("apellido".equals(cell.getStringCellValue())) {
                        posicion[0] = "apellido";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("email".equals(cell.getStringCellValue())) {
                        posicion[0] = "email";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("genero".equals(cell.getStringCellValue())) {
                        posicion[0] = "genero";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("llegada".equals(cell.getStringCellValue())) {

                        posicion[0] = "llegada";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("celular".equals(cell.getStringCellValue())) {
                        posicion[0] = "celular";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else {

                    }
                }
            }
        }
        HashTable b = new HashTable(habs.length);
        //Cogemos todas las filas de esa hoja
        int rowIndexEnd = hoja.getLastRowNum();
        Cell columna;
        for (int p = 1; p <= rowIndexEnd; p++) {
            row = hoja.getRow(p); // Obtiene la fila por índice
            n = 0;
            if (row != null) {
                int cellIndexStart = row.getFirstCellNum(); // Índice de la primera celda
                int cellIndexEnd = row.getLastCellNum();

                for (int cellIndex = cellIndexStart; cellIndex < cellIndexEnd; cellIndex++) {
                    columna = row.getCell(cellIndex); // Obtiene la celda por índice

                    String name = "";
                    String last_name = "";
                    String gener = "";
                    String email = "";
                    String phone = "";
                    String ride = "";
                    int num = 0;
                    //REcorremos todas las celdas

                    n++;
                    System.out.println(n);
                    //Cogemos la siguiente fila
                    //Segun el tipo de celda, usaremos uno u otra funcion
                    String[] orden = (String[]) ord.search2(n);
                    System.out.println(orden[0]);
                    switch (orden[0]) {
                        case "num_hab":
                            num = (int) columna.getNumericCellValue();
                            System.out.println(num);
                            break;
                        case "primer_nombre":
                            name = columna.getStringCellValue();
                            System.out.println(columna.getStringCellValue());
                            break;

                        case "apellido":
                            last_name = columna.getStringCellValue();
                            System.out.println(columna.getStringCellValue());
                            break;
                        case "email":
                            email = columna.getStringCellValue();
                            System.out.println(columna.getStringCellValue());
                            break;
                        case "genero":
                            gener = columna.getStringCellValue();
                            System.out.println(columna.getStringCellValue());
                            break;
                        case "celular":
                            phone = columna.getStringCellValue();
                            break;
                        case "llegada":
                            String a = String.valueOf(columna.getDateCellValue());
                            ride = a;
                            System.out.println("Fecha: " + a);
                            break;

                    }

                    try {
                        if ("".equals(ride)) {
                            User u = new User(name, last_name, gener, email, phone);
                            u.setRide(ride);
                            u.setNum(num);

                            habs[num - 1].setOccupied(true);
                            b.insert(u);
                        }
                    } catch (Exception e) {
                    }
                }

//                if (o != 0) {
//
//                    if (n == 1) {
//                        num = (int) columna.getNumericCellValue();
//                        System.out.println(num);
//
//                    } else if (n == 2) {
//                        name = columna.getStringCellValue();
////                        System.out.println(columna.getStringCellValue());
//
//                    } else if (n == 3) {
//                        last_name = columna.getStringCellValue();
////                        System.out.println(columna.getStringCellValue());
//                    } else if (n == 4) {
//                        email = columna.getStringCellValue();
////                        System.out.println(columna.getStringCellValue());
//                    } else if (n == 5) {
//                        gener = columna.getStringCellValue();
////                        System.out.println(columna.getStringCellValue());
//                    } else if (n == 6) {
//                        phone = columna.getStringCellValue();
////                        System.out.println(columna.getStringCellValue());
//                    } else if (n == 7) {
//                        String a = String.valueOf(columna.getDateCellValue());
//                        ride = a;
//
////                        System.out.println("Fecha: " + a);
//                    }
//                }
//            }
//            if (o != 0) {
//
//                User u = new User(name, last_name, gener, email, phone);
//                u.setRide(ride);
//                u.setNum(num);
//
//                habs[num - 1].setOccupied(true);
//                b.insert(u);
//
//            }
//            o++;}
            }
        }
        return b;
    }

    public void historico(XSSFSheet hoja, Bedroom habs[]) {
        Lista ord = new Lista();
        int n = 0;
        int rowIndex = 0; // Índice de la primera fila

        Row row = hoja.getRow(rowIndex); // Obtiene la primera fila

        if (row != null) {
            int cellIndexStart = row.getFirstCellNum(); // Índice de la primera celda
            int cellIndexEnd = row.getLastCellNum(); // Índice de la última celda

            for (int cellIndex = cellIndexStart; cellIndex < 10; cellIndex++) {
                Cell cell = row.getCell(cellIndex);
                n++;
                String[] posicion = new String[2];

                if (cell != null) {
                    if ("ci".equals(cell.getStringCellValue())) {
                        posicion[0] = "ci";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("primer_nombre".equals(cell.getStringCellValue())) {
                        posicion[0] = "primer_nombre";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("apellido".equals(cell.getStringCellValue())) {
                        posicion[0] = "apellido";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("email".equals(cell.getStringCellValue())) {
                        posicion[0] = "email";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("genero".equals(cell.getStringCellValue())) {
                        posicion[0] = "genero";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);

                    } else if ("llegada".equals(cell.getStringCellValue())) {
                        posicion[0] = "llegada";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else if ("num_hab".equals(cell.getStringCellValue())) {
                        posicion[0] = "salida";
                        String p = String.valueOf(n);
                        posicion[1] = p;
                        ord.addLast(posicion);
                    } else {

                    }

                }

            }
        }
        Iterator<Row> filas = hoja.iterator();
        Iterator<Cell> columnas;

        Row fila;
        Cell columna;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//            recorremos las filas
        Lista reservaciones = new Lista();
        int rowIndexEnd = hoja.getLastRowNum();

        for (int p = 1; p <= rowIndexEnd; p++) {
            row = hoja.getRow(p); // Obtiene la fila por índice
            n = 0;
            if (row != null) {
                int cellIndexStart = row.getFirstCellNum(); // Índice de la primera celda
                int cellIndexEnd = row.getLastCellNum();

                for (int cellIndex = cellIndexStart; cellIndex < cellIndexEnd; cellIndex++) {
                    columna = row.getCell(cellIndex); // Obtiene la celda por índice
                    int dni = 0;
                    String name = "";
                    String last_name = "";
                    String gener = "";
                    String email = "";
                    String ride = "";
                    int num = 0;

//                REcorremos todas las celdas
                    n++;
//                    Cogemos la siguiente fila

                    String[] orden = (String[]) ord.search2(n);
                    switch (orden[0]) {
                        case "ci":
                            double i = columna.getNumericCellValue();
                            String value = String.valueOf(i);
                            value = value.replace(".", "");
                            value = value.replace("E7", "");
                            dni = Integer.parseInt(value);
                            System.out.println(value);
                            break;
                        case "primer_nombre":
                            name = columna.getStringCellValue();
                            System.out.println(columna.getStringCellValue());
                            break;

                        case "apellido":
                            last_name = columna.getStringCellValue();
                            System.out.println(columna.getStringCellValue());
                            break;
                        case "email":
                            email = columna.getStringCellValue();
                            System.out.println(columna.getStringCellValue());
                            break;
                        case "genero":
                            gener = columna.getStringCellValue();
                            System.out.println(columna.getStringCellValue());
                            break;
                        case "llegada":
                            String a = String.valueOf(columna.getDateCellValue());
                            ride = a;

                            System.out.println("Fecha: " + a);
                            break;
                        case "num_hab":
                            num = (int) columna.getNumericCellValue();
                            System.out.println(num);
                            break;

                    }

                }
//            try {
//                if (!"".equals(departure)) {
//                    User u = new User(dni, name, last_name, gener, email, phone);
//                    u.setRide(ride);
//                    u.setDeparture(departure);
//                    Reservation r = new Reservation(u, type);
//                    reservaciones.addLast(r);
//                }
//            } catch (Exception e) {
//            }
//        }}
//        return reservaciones;
            }
        }
    }

    public void pruebas() {
        User u = (User) this.b.search("Tom", "Kew");
        u.show();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
